---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: open-ldap
  namespace: netbots
  labels:
    app.kubernetes.io/name:  open-ldap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open-ldap
  template:
    metadata:
      labels:
        app: open-ldap
    spec:
      containers:
        - image: 730335644419.dkr.ecr.us-east-1.amazonaws.com/open-ldap:latest
          imagePullPolicy: Always
          name: open-ldap
          ports:
          - containerPort:  389
            name:  openldap
          - containerPort:  636
            name:  openldaps
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: true
            runAsUser: 1000
            
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 128Mi
